[package]
name = "rugut"
version = "0.1.0"
authors = ["Nader Bahrami"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
